# Generated by Django 6.0.2 on 2026-03-08 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_board_id_alter_card_id_alter_column_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='fields',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='board',
            name='focusColumns',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='board',
            name='tags',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
