# Generated by Django 6.0.2 on 2026-03-08 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_board_fields_board_focuscolumns_board_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='attachments',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
