# Generated by Django 6.0.2 on 2026-03-24 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_card_attachments_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='config_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='column',
            name='tool_type',
            field=models.CharField(choices=[('none', 'None'), ('docker', 'Docker'), ('terraform', 'Terraform'), ('github_actions', 'GitHub Actions')], default='none', max_length=50),
        ),
    ]
