# Generated by Django 6.0.2 on 2026-03-26 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_card_config_data_column_tool_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='column',
            name='tool_type',
            field=models.CharField(choices=[('none', 'None'), ('docker', 'Docker'), ('kubernetes', 'Kubernetes'), ('terraform', 'Terraform'), ('github_actions', 'GitHub Actions'), ('aws', 'AWS'), ('gcp', 'GCP'), ('prometheus', 'Prometheus'), ('grafana', 'Grafana')], default='none', max_length=50),
        ),
    ]
