# Generated by Django 6.0.2 on 2026-03-26 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_add_new_tool_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='config_fields',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='template',
            name='tool_type',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
