"""
Default board templates seeded to every new user upon registration.
Structures follow the frontend BoardTemplate interface with FieldConfig and TagConfig.

Board-level templates have tool_type="" and config_fields=[].
Tool-specific templates have tool_type set and config_fields populated with the
input schema that CardDialog renders dynamically.
"""

DEFAULT_TEMPLATES = [
    # ── Existing board templates (unchanged structure, new keys added) ──────
    {
        "name": "Containerized Web App",
        "description": "Standard Docker image built and deployed via CI/CD",
        "icon": "Box",
        "columns": ["Docker Build", "Terraform Infra", "GitHub Actions Deploy"],
        "fields": [
            {"id": "environment", "name": "Environment", "type": "select",
             "required": True, "options": ["Production", "Staging", "Development"],
             "placeholder": "Select environment"},
            {"id": "owner", "name": "Owner", "type": "text",
             "required": False, "placeholder": "Responsible team"},
        ],
        "tags": [
            {"id": "frontend", "name": "Frontend", "color": "hsl(210, 80%, 60%)"},
            {"id": "backend", "name": "Backend", "color": "hsl(150, 70%, 50%)"},
        ],
        "tool_type": "",
        "config_fields": [],
    },
    {
        "name": "Serverless Infrastructure",
        "description": "Provision and deploy cloud-native serverless components",
        "icon": "Cloud",
        "columns": ["Terraform Base", "GitHub Actions CI", "Terraform App"],
        "fields": [
            {"id": "region", "name": "Cloud Region", "type": "text",
             "required": True, "placeholder": "us-east-1"},
            {"id": "runtime", "name": "Runtime", "type": "select",
             "required": False, "options": ["Node.js", "Python", "Go"],
             "placeholder": "Select runtime"},
        ],
        "tags": [
            {"id": "api", "name": "API Gateway", "color": "hsl(45, 90%, 55%)"},
            {"id": "db", "name": "Database", "color": "hsl(280, 60%, 60%)"},
        ],
        "tool_type": "",
        "config_fields": [],
    },
    {
        "name": "Custom Integration Pipeline",
        "description": "Configure your own deployment workflows from scratch",
        "icon": "Wrench",
        "columns": ["Setup", "Docker Container", "GitHub Actions"],
        "fields": [
            {"id": "trigger", "name": "Trigger Event", "type": "select",
             "required": False, "options": ["Push", "PR", "Manual"],
             "placeholder": "Trigger"},
        ],
        "tags": [
            {"id": "experimental", "name": "Experimental", "color": "hsl(0, 80%, 60%)"},
        ],
        "tool_type": "",
        "config_fields": [],
    },
    {
        "name": "Kubernetes Full Stack",
        "description": "Docker build → K8s deploy with Prometheus & Grafana monitoring",
        "icon": "Container",
        "columns": ["Docker Build", "Kubernetes Deploy", "Prometheus Alerts", "Grafana Dashboard"],
        "fields": [
            {"id": "app_name", "name": "App Name", "type": "text", "required": True, "placeholder": "my-app"},
            {"id": "environment", "name": "Environment", "type": "select", "required": True,
             "options": ["dev", "staging", "production"], "placeholder": "Select environment"},
            {"id": "namespace", "name": "K8s Namespace", "type": "text", "required": False, "placeholder": "default"},
        ],
        "tags": [
            {"id": "k8s", "name": "Kubernetes", "color": "hsl(210, 80%, 60%)"},
            {"id": "monitoring", "name": "Monitoring", "color": "hsl(45, 90%, 55%)"},
        ],
        "tool_type": "",
        "config_fields": [],
    },
    {
        "name": "AWS Cloud Infrastructure",
        "description": "Provision EKS, IAM, and S3 on AWS with Terraform",
        "icon": "Cloud",
        "columns": ["AWS Terraform", "Kubernetes Deploy", "GitHub Actions CI"],
        "fields": [
            {"id": "cluster_name", "name": "Cluster Name", "type": "text", "required": True, "placeholder": "prod-cluster"},
            {"id": "region", "name": "AWS Region", "type": "text", "required": True, "placeholder": "us-east-1"},
            {"id": "instance_type", "name": "Instance Type", "type": "select", "required": False,
             "options": ["t3.small", "t3.medium", "t3.large", "m5.xlarge"], "placeholder": "t3.medium"},
            {"id": "environment", "name": "Environment", "type": "select", "required": True,
             "options": ["dev", "staging", "production"]},
        ],
        "tags": [
            {"id": "aws", "name": "AWS", "color": "hsl(30, 90%, 55%)"},
            {"id": "iac", "name": "IaC", "color": "hsl(150, 70%, 50%)"},
        ],
        "tool_type": "",
        "config_fields": [],
    },
    {
        "name": "GCP Cloud Infrastructure",
        "description": "Provision GKE, Cloud SQL on GCP with Terraform",
        "icon": "Server",
        "columns": ["GCP Terraform", "Kubernetes Deploy", "Prometheus Monitoring"],
        "fields": [
            {"id": "project_id", "name": "GCP Project ID", "type": "text", "required": True, "placeholder": "my-gcp-project"},
            {"id": "cluster_name", "name": "Cluster Name", "type": "text", "required": True, "placeholder": "prod-cluster"},
            {"id": "region", "name": "GCP Region", "type": "text", "required": True, "placeholder": "us-central1"},
            {"id": "machine_type", "name": "Machine Type", "type": "select", "required": False,
             "options": ["e2-small", "e2-standard-2", "e2-standard-4", "n1-standard-4"], "placeholder": "e2-standard-2"},
            {"id": "environment", "name": "Environment", "type": "select", "required": True,
             "options": ["dev", "staging", "production"]},
        ],
        "tags": [
            {"id": "gcp", "name": "GCP", "color": "hsl(210, 70%, 55%)"},
            {"id": "iac", "name": "IaC", "color": "hsl(150, 70%, 50%)"},
        ],
        "tool_type": "",
        "config_fields": [],
    },

    # ── Tool-specific templates (tool_type set, config_fields populated) ────
    {
        "name": "Docker",
        "description": "Build and run containerized applications",
        "icon": "Box",
        "columns": [],
        "fields": [],
        "tags": [],
        "tool_type": "docker",
        "config_fields": [
            {"id": "base_image", "label": "Base Image", "type": "text",
             "placeholder": "python:3.11-slim", "options": [], "required": False},
            {"id": "expose_port", "label": "Expose Port", "type": "number",
             "placeholder": "8000", "options": [], "required": False},
            {"id": "entrypoint", "label": "Entrypoint", "type": "text",
             "placeholder": "python", "options": [], "required": False},
            {"id": "entrypoint_args", "label": "Entrypoint Args", "type": "text",
             "placeholder": "manage.py runserver 0.0.0.0:8000", "options": [], "required": False},
            {"id": "environment", "label": "Environment", "type": "select",
             "placeholder": "", "options": ["development", "staging", "production"], "required": False},
            {"id": "include_db", "label": "Include Postgres DB", "type": "checkbox",
             "placeholder": "", "options": [], "required": False},
            {"id": "include_redis", "label": "Include Redis", "type": "checkbox",
             "placeholder": "", "options": [], "required": False},
        ],
    },
    {
        "name": "Kubernetes",
        "description": "Deploy and manage containerized workloads on Kubernetes",
        "icon": "Container",
        "columns": [],
        "fields": [],
        "tags": [],
        "tool_type": "kubernetes",
        "config_fields": [
            {"id": "app_name", "label": "App Name", "type": "text",
             "placeholder": "my-app", "options": [], "required": True},
            {"id": "namespace", "label": "Namespace", "type": "text",
             "placeholder": "default", "options": [], "required": False},
            {"id": "image_repo", "label": "Image Repository", "type": "text",
             "placeholder": "myrepo/myapp", "options": [], "required": False},
            {"id": "image_tag", "label": "Image Tag", "type": "text",
             "placeholder": "latest", "options": [], "required": False},
            {"id": "replicas", "label": "Replicas", "type": "number",
             "placeholder": "2", "options": [], "required": False},
            {"id": "expose_port", "label": "Container Port", "type": "number",
             "placeholder": "8000", "options": [], "required": False},
            {"id": "cpu_limit", "label": "CPU Limit", "type": "text",
             "placeholder": "500m", "options": [], "required": False},
            {"id": "memory_limit", "label": "Memory Limit", "type": "text",
             "placeholder": "256Mi", "options": [], "required": False},
            {"id": "service_type", "label": "Service Type", "type": "select",
             "placeholder": "", "options": ["ClusterIP", "NodePort", "LoadBalancer"], "required": False},
            {"id": "hostname", "label": "Ingress Hostname", "type": "text",
             "placeholder": "app.example.com", "options": [], "required": False},
            {"id": "enable_tls", "label": "Enable TLS", "type": "checkbox",
             "placeholder": "", "options": [], "required": False},
            {"id": "enable_prometheus_scrape", "label": "Enable Prometheus Scrape",
             "type": "checkbox", "placeholder": "", "options": [], "required": False},
        ],
    },
    {
        "name": "AWS",
        "description": "Provision EKS clusters and AWS infrastructure with Terraform",
        "icon": "Cloud",
        "columns": [],
        "fields": [],
        "tags": [],
        "tool_type": "aws",
        "config_fields": [
            {"id": "cluster_name", "label": "Cluster Name", "type": "text",
             "placeholder": "app-cluster", "options": [], "required": True},
            {"id": "region", "label": "AWS Region", "type": "text",
             "placeholder": "us-east-1", "options": [], "required": False},
            {"id": "instance_type", "label": "Instance Type", "type": "select",
             "placeholder": "", "options": ["t3.small", "t3.medium", "t3.large", "m5.xlarge"], "required": False},
            {"id": "desired_nodes", "label": "Desired Nodes", "type": "number",
             "placeholder": "2", "options": [], "required": False},
            {"id": "min_nodes", "label": "Min Nodes", "type": "number",
             "placeholder": "1", "options": [], "required": False},
            {"id": "max_nodes", "label": "Max Nodes", "type": "number",
             "placeholder": "4", "options": [], "required": False},
            {"id": "environment", "label": "Environment", "type": "select",
             "placeholder": "", "options": ["dev", "staging", "production"], "required": False},
            {"id": "include_s3", "label": "Include S3 Bucket", "type": "checkbox",
             "placeholder": "", "options": [], "required": False},
            {"id": "k8s_version", "label": "Kubernetes Version", "type": "text",
             "placeholder": "1.29", "options": [], "required": False},
        ],
    },
    {
        "name": "GCP",
        "description": "Provision GKE clusters and GCP infrastructure with Terraform",
        "icon": "Server",
        "columns": [],
        "fields": [],
        "tags": [],
        "tool_type": "gcp",
        "config_fields": [
            {"id": "project_id", "label": "GCP Project ID", "type": "text",
             "placeholder": "my-gcp-project", "options": [], "required": True},
            {"id": "cluster_name", "label": "Cluster Name", "type": "text",
             "placeholder": "app-cluster", "options": [], "required": True},
            {"id": "region", "label": "GCP Region", "type": "text",
             "placeholder": "us-central1", "options": [], "required": False},
            {"id": "machine_type", "label": "Machine Type", "type": "select",
             "placeholder": "", "options": ["e2-small", "e2-standard-2", "e2-standard-4", "n1-standard-4"], "required": False},
            {"id": "node_count", "label": "Node Count", "type": "number",
             "placeholder": "2", "options": [], "required": False},
            {"id": "min_nodes", "label": "Min Nodes", "type": "number",
             "placeholder": "1", "options": [], "required": False},
            {"id": "max_nodes", "label": "Max Nodes", "type": "number",
             "placeholder": "4", "options": [], "required": False},
            {"id": "environment", "label": "Environment", "type": "select",
             "placeholder": "", "options": ["dev", "staging", "production"], "required": False},
            {"id": "include_cloud_sql", "label": "Include Cloud SQL", "type": "checkbox",
             "placeholder": "", "options": [], "required": False},
        ],
    },
    {
        "name": "Prometheus",
        "description": "Configure metrics scraping and alerting rules",
        "icon": "Activity",
        "columns": [],
        "fields": [],
        "tags": [],
        "tool_type": "prometheus",
        "config_fields": [
            {"id": "app_name", "label": "App Name", "type": "text",
             "placeholder": "my-app", "options": [], "required": True},
            {"id": "app_host", "label": "App Host:Port", "type": "text",
             "placeholder": "app:8000", "options": [], "required": False},
            {"id": "metrics_path", "label": "Metrics Path", "type": "text",
             "placeholder": "/metrics", "options": [], "required": False},
            {"id": "namespace", "label": "K8s Namespace", "type": "text",
             "placeholder": "default", "options": [], "required": False},
            {"id": "scrape_interval", "label": "Scrape Interval", "type": "text",
             "placeholder": "15s", "options": [], "required": False},
            {"id": "environment", "label": "Environment", "type": "select",
             "placeholder": "", "options": ["dev", "staging", "production"], "required": False},
            {"id": "error_rate_threshold", "label": "Error Rate Alert Threshold", "type": "text",
             "placeholder": "0.05", "options": [], "required": False},
            {"id": "latency_threshold_seconds", "label": "Latency Threshold (s)", "type": "number",
             "placeholder": "2", "options": [], "required": False},
            {"id": "memory_threshold", "label": "Memory Threshold (0-1)", "type": "text",
             "placeholder": "0.85", "options": [], "required": False},
        ],
    },
    {
        "name": "Grafana",
        "description": "Generate Grafana dashboards and datasource configuration",
        "icon": "BarChart",
        "columns": [],
        "fields": [],
        "tags": [],
        "tool_type": "grafana",
        "config_fields": [
            {"id": "app_name", "label": "App Name", "type": "text",
             "placeholder": "my-app", "options": [], "required": True},
            {"id": "namespace", "label": "K8s Namespace", "type": "text",
             "placeholder": "default", "options": [], "required": False},
            {"id": "prometheus_host", "label": "Prometheus Host:Port", "type": "text",
             "placeholder": "prometheus:9090", "options": [], "required": False},
            {"id": "scrape_interval", "label": "Scrape Interval", "type": "text",
             "placeholder": "15s", "options": [], "required": False},
            {"id": "refresh_interval", "label": "Dashboard Refresh", "type": "select",
             "placeholder": "", "options": ["10s", "30s", "1m", "5m"], "required": False},
        ],
    },
    {
        "name": "GitHub Actions",
        "description": "Generate CI/CD pipeline workflows",
        "icon": "GitBranch",
        "columns": [],
        "fields": [],
        "tags": [],
        "tool_type": "github_actions",
        "config_fields": [
            {"id": "branch", "label": "Branch", "type": "text",
             "placeholder": "main", "options": [], "required": False},
            {"id": "image_name", "label": "Image Name", "type": "text",
             "placeholder": "my-app", "options": [], "required": False},
            {"id": "test_command", "label": "Test Command", "type": "text",
             "placeholder": "pytest", "options": [], "required": False},
        ],
    },
    {
        "name": "Terraform",
        "description": "Generic Terraform infrastructure provisioning",
        "icon": "Server",
        "columns": [],
        "fields": [],
        "tags": [],
        "tool_type": "terraform",
        "config_fields": [
            {"id": "cluster_name", "label": "Cluster Name", "type": "text",
             "placeholder": "app-cluster", "options": [], "required": False},
            {"id": "region", "label": "Region", "type": "text",
             "placeholder": "us-east-1", "options": [], "required": False},
            {"id": "instance_type", "label": "Instance Type", "type": "text",
             "placeholder": "t3.medium", "options": [], "required": False},
            {"id": "environment", "label": "Environment", "type": "select",
             "placeholder": "", "options": ["dev", "staging", "production"], "required": False},
        ],
    },
]
