[project]
name = "contextual-kanban-backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "asgiref==3.11.1",
    "django==6.0.2",
    "django-cors-headers==4.9.0",
    "django-environ==0.13.0",
    "django-extensions>=4.1",
    "djangorestframework==3.16.1",
    "djangorestframework-simplejwt==5.5.1",
    "jinja2>=3.1.6",
    "psycopg2==2.9.11",
    "pydot>=4.0.1",
    "pyjwt==2.11.0",
    "python-dotenv==1.2.2",
    "sqlparse==0.5.5",
    "tzdata==2025.3",
]
